// scripts/build-sw.mjs — build:sw
//
// Bundles the REAL Node Zero G-D service worker (src/sw/sw-source.ts + gd-* + @noble crypto)
// into public/sw.js, so the DEPLOYED /sw.js is the ACTUAL verifier — not the 3940B placeholder.
//
// Why this is mint-critical (Archie #142294): the signer signs the served manifest, which includes
// /sw.js. If /sw.js is the placeholder, the signed manifest ships a stub-SW and the mint recognizes
// Node Zero via a verifier-that-isn't-there = G-D theater at deploy. So public/sw.js MUST be the real
// bundle at build time, the signer signs THAT, and dev-first-verify exercises the deployed real SW.
//
// public/sw.js is a GENERATED artifact (gitignored) — the source of truth is src/sw/sw-source.ts.
// Run: `npm run build:sw` (also runs first in `npm run build`).

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const result = await build({
  entryPoints: [resolve(root, 'src/sw/sw-source.ts')],
  outfile: resolve(root, 'public/sw.js'),
  bundle: true,
  format: 'iife',          // a service worker is a classic worker script, not an ES module
  platform: 'browser',
  target: ['es2020'],
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  banner: {
    js: '/* svrnty Node Zero G-D verifier — GENERATED by build:sw from src/sw/sw-source.ts. DO NOT EDIT. */',
  },
  metafile: true,
}).catch((e) => {
  console.error('[build:sw] FAILED:', e?.message ?? e);
  process.exit(1);
});

const outKey = Object.keys(result.metafile.outputs).find((k) => k.endsWith('public/sw.js'));
const bytes = outKey ? result.metafile.outputs[outKey].bytes : 0;
console.log(`[build:sw] public/sw.js ← src/sw/sw-source.ts  (${(bytes / 1024).toFixed(1)} KB, minified IIFE)`);
